import Head from 'next/head'
import styles from '../styles/Main.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Next 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2>Next 2023</h2>
      </main>
    </>
  )
}
